---
title: "Reproducible research Assignment"
author: "Shubham Joshi"
date: "27/04/2023"
output: html_document
---



# Game Of Thrones

**Game of Thrones** is an American fantasy drama television series created by **David Benioff** and **D. B. Weiss**. The series is based on **George R. R. Martin's** series of fantasy novels, A Song of Ice and Fire. The series takes place on the fictional continents of Westeros and Essos, and chronicles the power struggles among noble families as they fight for control of the Iron Throne of the Seven Kingdoms. The series starts when House Stark, led by **Lord Eddard** "Ned" Stark (Sean Bean), is drawn into schemes surrounding **King Robert Baratheon** (Mark Addy).[1]

The series premiered on April 17, 2011, on HBO. **David Benioff** and **D. B. Weiss** both serve as executive producers, along with **Carolyn *Strauss**, **Frank Doelger**, Bernadette Caulfield, and George R. R. Martin.[2][3] Filming for the series took place in a number of locations, including Croatia, Northern Ireland, Iceland, and Spain.[4][5][6] Episodes were broadcast on Sunday at 9:00 pm Eastern Time,[7][8] and the episodes are between 50 and 82 minutes in length.[9] All eight seasons are available on DVD, Blu-ray and Ultra HD Blu-ray.

The series concluded with its eighth season, which premiered on April 14, 2019, and consisted of six episodes.[10][11][12] The show's episodes have won numerous awards including four Primetime Emmy Awards for Outstanding Drama Series.[3] During the course of the series, 73 episodes of Game of Thrones aired over eight seasons, between April 17, 2011, and May 19, 2019.